
default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: 123456
  pool: 20
  host: localhost

development:
  <<: *default
  database: rails4_app_development

test:
  <<: *default
  database: rails4_app_test

production:
  password:
  database: rails4_app_production
